### PR TITLE
Add more questions

### PR DESCRIPTION
**Pull request by zineanteoh**
added more questions & did some reorganization: 

- Are you a first-time hacker? (Beginner hackers are warmly welcomed!) Yes/No
- Why would you like to attend VandyHacks? Text answer
- Which tech industry do you want to get into Text answer
- What tech stack, if any, are you familiar with? Text answer
- What are you passionate about? Text answer
- Will you be staying overnight in the venue and thus need access to shower? Yes/No
- Are you a U.S. Citizen, Permanent Resident, or granted the status of Immigrant, Refugee, Asylee or Deferred Action for Childhood Arrival (DACA), by the Bureau of Citizenship and Immigration Services? Yes/No

### CODE REVIEW

**Comment by aadibajpai** [comment]
> added more questions & did some reorganization:
> 
> * Are you a first-time hacker? (Beginner hackers are warmly welcomed!) Yes/No
> * Why would you like to attend VandyHacks? Text answer
> * Which tech industry do you want to get into Text answer
> * What tech stack, if any, are you familiar with? Text answer
> * What are you passionate about? Text answer
> * Will you be staying overnight in the venue and thus need access to shower? Yes/No
> * Are you a U.S. Citizen, Permanent Resident, or granted the status of Immigrant, Refugee, Asylee or Deferred Action for Childhood Arrival (DACA), by the Bureau of Citizenship and Immigration Services? Yes/No

why do we need these fields? I am hesitant to add more info given we are already in prod. Did the presidents sign off on these changes?

**Comment by zineanteoh** [comment]
Yes we did @KarolinaGroszewska

**Comment by KarolinaGroszewska** [comment]
There's a couple of reasons why we are choosing to add these, especially with us already in prod. 
1. We offer the hacker DB to sponsors outside of resumes, asking additional questions is more of a benefit to them and was requested by Jack. 
2. We need to plan for prizes. Prizes cannot be given out to international students by Vandy because it involves contacting the international tax office and potentially jeopardizing the students' visa status. I think it is BS, but Greg said international students and prizes are almost impossible to do.
3. We will supplement the information of those already submitted as needed, including reaching out to them personally. The inconvenience of ~35 people needing to respond to 2-3 more sentences is not ideal, but it beats out losing this much data (and the potential legal consequences VH could face)

**Review by aadibajpai — APPROVED** [review]
I am hoping the backend changes are fine.

The accommodation needs question could be improved, if you want to do it as a part of this that works too

**Comment by KarolinaGroszewska** [comment]
Am good to update that now, limits the # of times we’re going into a prod
DB.

**Comment by zineanteoh** [comment]
i just realized i made a spelling mistake... once pushed to prod i'll rename the existing fields in mongodb to keep things consistent

**Review by KarolinaGroszewska — APPROVED** [review]
looks good, thank you zi and aadi for your work on this :))

**Pull request merged**
