### PR TITLE
refactor assignRole to manageRole

### PR DESCRIPTION
**Pull request by aadibajpai**
since we will start defaulting users to hackers, this converts the assign role page to be a general page to view all users and be able to modify roles as needed while also being able to see their name and email.

previously we could just see names which could technically lead to error if say, hacker and judge have the same or wrong name.

curious if there's a better way to format the text

### CODE REVIEW

**Comment by aadibajpai** [comment]
for some reason the text is cut off

**Comment by aadibajpai** [comment]
prob should add a way to show that dropdown has changed the role if person changes it

**Comment by Ace314159** [comment]
It would be nice to have an indicator to show what roles you've changed before hitting submit

**Comment by Ace314159** [comment]
We should have a way to select no role, since if you assign a role to someone who had no role before, there's no way to undo.

**Comment by aadibajpai** [comment]
> We should have a way to select no role, since if you assign a role to someone who had no role before, there's no way to undo.

yes I experimented with adding the clear button, but going forward we expect everyone to have a role so the clear button will cause more harm because it will also allow you to clear the role from someone who already has one assigned which could lead to errors. Currently, you could just refresh to reset assigning a role to someone who doesn't

**Comment by SamLee514** [comment]
Might be a bit far down the list of nice-to-haves but a bulk undo would be nice. Or like reverting back to a previous state. Other than that, yeah looks good

**Comment by SamLee514** [comment]
Agree that if we are saying hacker is default then the no-role is a bit moot. I do think indicating what has been changed before hitting submit should be a high priority item.

**Comment by nkalupahana** [comment]
> Might be a bit far down the list of nice-to-haves but a bulk undo would be nice. Or like reverting back to a previous state. Other than that, yeah looks good

bulk undo is cmd+r

**Comment by aadibajpai** [comment]
> 

it should display what has been changed, the field will glow yellow. Try it.
image

**Comment by nkalupahana** [comment]
Kids these days are so entitled. Back in my day, we walked up the hill both ways to the server farm. Now they're asking for things like... "bulk undo"?? what even is this

**Comment by aadibajpai** [comment]
> Kids these days are so entitled. Back in my day, we walked up the hill both ways to the server farm. Now they're asking for things like... "bulk undo"?? what even is this

@lab126

**Comment by SamLee514** [comment]
ye but what if already pressed submit 🥺

**Comment by aadibajpai** [comment]
also, just fixed submit button working. Note that previously it was mutating 'api/assign', even though there was no 'api/assign'

**Review by Ace314159 — APPROVED** [review]

**Comment by aadibajpai** [comment]
I'll merge now, but there's a couple of things we can do more—a clear button is easy to do and also a search filter. Also right now, the orange glow will not disappear after pressing submit which I suspect is something we need to figure out the swr stuff to get working well cc: @SamLee514 resident swr expert

**Pull request merged**
