### PR TITLE
Refactor Organizer Page

### PR DESCRIPTION
**Pull request by jacoblurie29**

### CODE REVIEW

**Comment by abi-kothapalli** [comment]
@jacoblurie29 Rebase with main to fix the CI issue

**Comment by abi-kothapalli** [comment]
Also, add some details to the PR on what you actually changed, doesnt need to be super long. If you actually changed anything on the frontend then include screenshots as well. Lmk when u do that and I can review the pr

**Comment by zineanteoh** [comment]
@jacoblurie29 a dónde es tu PR message? 👿

**Review by zineanteoh — APPROVED** [review]
LGTM!

**Pull request merged**
